[features]
seeds = false
[programs.devnet]
myepicproject = "8UbJVF2h6sS1YmiP3acJKdC9YUro1yao1AqP7XnZeAaC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/techie_teee/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
